Io 136 v5 contribution receive date calculation
compucorp/uk.co.compucorp.manualdirectdebit pull request #236
Opened 2021-04-22 14:43 UTC by erawat

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2021-04-26 23:01 UTC, omarabuhussein requested changes

2021-04-26 23:03 UTC, omarabuhussein commented
also @erawat can you write the details of the new date calculation logic instead of just mentioning that it is "implemented as per Membership Extras v5",

2021-05-07 13:18 UTC, erawat commented on CRM/ManualDirectDebit/Test/Helper/PaymentPlanTrait.php
> +trait CRM_ManualDirectDebit_Test_Helper_PaymentPlanTrait {
@omarabuhussein  I did not re-invest the wheel here, the mocking has already existed, I only decouple them and put in the trait. Should we remove it and then refactor to use the ME stuff directly?

2021-05-07 13:18 UTC, erawat commented on CRM/ManualDirectDebit/Test/Helper/PaymentPlanTrait.php
> +  private function setupPlan($membershipStartDate, $firstInstalmentReceiveDate, array $params) {
@omarabuhussein  the reason same as above.

2021-05-07 13:29 UTC, omarabuhussein commented on CRM/ManualDirectDebit/Test/Helper/PaymentPlanTrait.php
> +trait CRM_ManualDirectDebit_Test_Helper_PaymentPlanTrait {
> Should we remove it and then refactor to use the ME stuff directly?

yes

2021-05-07 13:33 UTC, erawat commented on CRM/ManualDirectDebit/Test/Helper/PaymentPlanTrait.php
> +trait CRM_ManualDirectDebit_Test_Helper_PaymentPlanTrait {
@omarabuhussein  cool beans

2021-05-10 11:35 UTC, erawat commented on CRM/ManualDirectDebit/Test/Helper/PaymentPlanTrait.php
> +trait CRM_ManualDirectDebit_Test_Helper_PaymentPlanTrait {
@omarabuhussein  the function has been refactored to re-use the paymentPlanOrder fabricator, I left the traits as I don't want to repeat the code for fabricating on other contribution received date classes.

2021-05-10 15:24 UTC, omarabuhussein approved these changes

2021-07-16 10:48 UTC, merged